### ISSUE TITLE
Error converting value "loadedByProxy"

### ISSUE THREAD

**Issue by jcarenton** [sendinblue/APIv3-csharp-library#50]
Changes in Apple’s Mail Privacy Protection

Method GetEmailEventReport failed. 

**Error converting value "loadedByProxy" to type 'sib_api_v3_sdk.Model.GetEmailEventReportEvents+EventEnum'. Path 'events[0].event', line 1, position 272.**
**Exception sib_api_v3_sdk.Client.ApiException on assembly sib_api_v3_sdk.**
Stack Trace:    at sib_api_v3_sdk.Client.ApiClient.Deserialize(IRestResponse response, Type type)
   at sib_api_v3_sdk.Api.SMTPApi.GetEmailEventReportWithHttpInfo(Nullable`1 limit, Nullable`1 offset, String startDate, String endDate, Nullable`1 days, String email, String _event, String tags, String messageId, Nullable`1 templateId)
   at sib_api_v3_sdk.Api.SMTPApi.GetEmailEventReport(Nullable`1 limit, Nullable`1 offset, String startDate, String endDate, Nullable`1 days, String email, String _event, String tags, String messageId, Nullable`1 templateId)

**Comment by amitsendinblue** [comment]
Please try with latest release 3.3.0

**Comment by jcarenton** [comment]
Thank you for information, but since the issue #19 (not resolved) we have moved on source code and we no longer use release and nuget package.
