### ISSUE TITLE
Create Campain endpoint > header field is not optional

### ISSUE THREAD

**Issue by dvdnhm** [sendinblue/APIv3-csharp-library#51]
I am trying to implement CreateEmailCampaign endpoint in our system. I don't really have anything to say in the header, so I want to leave it empty... I tried null, "", " " as header value.... but I keep getting the error below. I am surprised that you haven't considered this possibility... 

Error Message:
Exception has occurred: CLR/sib_api_v3_sdk.Client.ApiException
Exception thrown: 'sib_api_v3_sdk.Client.ApiException' in sib_api_v3_sdk.dll: 'Error calling CreateEmailCampaign: {"code":"missing_parameter","message":"header is missing"}'
   at sib_api_v3_sdk.Api.EmailCampaignsApi.CreateEmailCampaignWithHttpInfo(CreateEmailCampaign emailCampaigns)
   at sib_api_v3_sdk.Api.EmailCampaignsApi.CreateEmailCampaign(CreateEmailCampaign emailCampaigns)
   at API.Services.MailCampainService.create(String personID, Message message, String environmentName)

**Comment by amitsendinblue** [comment]
Please try below line of code with latest version, I am able to pass null in headers, please let us know if you still face the issue.
```var apiInstance = new EmailCampaignsApi();
            string tag = "Test_Tag";
            string sender_Name = "John";
            string sender_Email = "example@example.com";
            CreateEmailCampaignSender sender = new CreateEmailCampaignSender(sender_Name, sender_Email);
            string name = "Test_Campaign";
            string htmlContent = "<h1>Hello this is test</h1>";
            string htmlUrl = null;
            long? templateId = null;
            string scheduledAt = "2029-12-24T16:03:51.000+05:30";
            string subject = "Test Subject";
            string replyTo = "example@example.com";
            string toField = "John";
            List<long?> exclusionListIds = new List<long?>();
            exclusionListIds.Add(4);
            List<long?> listIds = new List<long?>();
            listIds.Add(2);
            CreateEmailCampaignRecipients recipients = new CreateEmailCampaignRecipients(exclusionListIds, listIds);
            string attachmentUrl = null;
            bool? inlineImageActivation = false;
            bool? mirrorActive = false;
            string footer = null;
            string header = null;
            string utmCampaign = null;
            JObject _params = null;
            try
            {
                var emailCampaigns = new CreateEmailCampaign(tag, sender, name, htmlContent, htmlUrl, templateId, scheduledAt, subject, replyTo, toField, recipients, attachmentUrl, inlineImageActivation, mirrorActive, footer, header, utmCampaign, _params);
                CreateModel result = apiInstance.CreateEmailCampaign(emailCampaigns);
                Debug.WriteLine(result.ToJson());
                Console.WriteLine(result.ToJson());
                Console.ReadLine();
            }
            catch (Exception e)
            {
                Debug.WriteLine(e.Message);
                Console.WriteLine(e.Message);
                Console.ReadLine();
            }
