### ISSUE TITLE
CreateContact crash

### ISSUE THREAD

**Issue by ttj74** [sendinblue/APIv3-csharp-library#73]
It has been working for months, but since around 3 weeks it keeps crashing about 30% of the time. The only thing we has done is moving the server to a new hyper-v with AMD cpu's - the old one had Intel cpu's. I have tried many things but when I run the application on my Windows 11 PC it works, but on the server (Windows 2019) it keeps crashing often. I have tried with .Net 4.7.2 and 4.8, and x64 or x86 CPU setting. 

I get this error from the sib_api_v3_sdk:
Message: One or more errors occurred.
Stacktrace: 
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at sib_api_v3_sdk.Client.ApiClient.CallApi(String path, Method method, List`1 queryParams, Object postBody, Dictionary`2 headerParams, Dictionary`2 formParams, Dictionary`2 fileParams, Dictionary`2 pathParams, String contentType)
   at sib_api_v3_sdk.Api.ContactsApi.CreateContactWithHttpInfo(CreateContact createContact)
   at sib_api_v3_sdk.Api.ContactsApi.CreateContact(CreateContact createContact)

The data I send is not an issue, since when I try later or at my PC it is being send and the contact created.

Thanks for you help.
Thomas

**Comment by amitsendinblue** [comment]
Hey @ttj74,
We recently released the newer version of our SDK - https://www.nuget.org/packages/brevo_csharp, could you please try it once and let us know if the issue still persist.
Thanks
